### ISSUE TITLE
Checking for essentials.balancetop.exclude

### ISSUE THREAD

**Issue by x1p** [PlaceholderAPI/Vault-Expansion#19]
### Issue

I noticed that LuckPerms checks every 30 secs for certain permissions I don't have.
![Screenshot093634](https://user-images.githubusercontent.com/28690790/102594204-2c1b3a80-4116-11eb-9aad-cc8241ebc4a2.png)

I don't have essentials. So I was curious what could be the cause of this.
I found out that papi causes this. Searching the internet I found this PR:
https://github.com/PlaceholderAPI/Vault-Expansion/pull/13
I'm not sure why this is happening but I find this unnecessary.

### Expected behaviour

Apparently papi fails to check that I don't use essentials at all.

### Actual behaviour

Check essentials.balancetop.exclude for every known player. This can be quite extensive when running in a hub server.

### How to reproduce

1. Run: `lp verbose on`
or more specifically:
2. `lp verbose on essentials`

### `/papi dump` output

https://paste.helpch.at/duraqecote

**Comment by darbyjack** [comment]
The Vault expansion is having it's baltop placeholders removed soon. I'm waiting on a PR from Essentials to be merged so that I can utilize EssX new API inside of the EssX expansion.

**Comment by GenSecrets** [comment]
Can confirm this as a continued issue. Our server network has been in maintenance for ~roughly 3 days now on a fallback server due to severe lag and once we traced it, it seems to sourced from this baltop issue.

As a temporary work around for our server and any others who need: In the PAPI config.yml it should generate a "vault" section, you can disable the baltop hooks there. 

The major source of our lag was the fact that it was checking thousands of offline players in roughly the past ~3y or however long Bukkit had information on. If these offline player lists are generated and checked on a scheduled basis, I would recommend adding configurable time limits such as "offline players from the past 90 days" etc

**Comment by BlitzOffline** [comment]
@GenSecrets 

As glare said, these are being removed. In fact they were removed in versions newer than 1.5.2 I believe.

It was also moved to the essentials expansion (and uses essentials's baltop now instead). You can find a development build of this expansion in our discord: discord.gg/helpchat in the #placeholder-api channel. it should be pinned.
