### ISSUE TITLE
vault ranking variable

### ISSUE THREAD

**Issue by 157946a** [PlaceholderAPI/Vault-Expansion#24]
The ranking variable of vault cannot be used. Regardless of whether I input a number or id or something else, the content of 0.0 is displayed, not the player's money, placeholderapi is the latest version, and extensions and plugins are also the latest version.

**Comment by Starmism** [comment]
Please elaborate on which placeholder specifically is causing the issue.

**Comment by 157946a** [comment]
%vault_eco_balance%
%vault_eco_balance_commas%
%vault_eco_balance_fixed%
%vault_eco_balance_formatted%
Except for these few, other economic variables cannot be used. All returned are 0. No matter how to fill in, the following is the variable that returns 0 for whatever value is filled.
%vault_eco_top_balance_#%
%vault_eco_top_balance_fixed_#%
%vault_eco_top_balance_formatted_#%
%vault_eco_top_balance_commas_#%
%vault_eco_top_player_#%
%vault_eco_top_rank%

**Comment by Starmism** [comment]
You can try using them if you download version 1.5.2 of this expansion. You also have to enable a config setting since they tend to cause a lot of lag.

We are currently working on placing these placeholders into the Essentials expansion since Essentials provides a very nice and performant interface to work with, the placeholders were laggy anyways, and since these placeholders only worked with the Essentials economy anyways.

**Comment by 157946a** [comment]
I tested it, except that %vault_eco_top_rank% cannot be used, the variables are displayed directly, no value is displayed, everything else is normal

**Comment by BlitzOffline** [comment]
Hello,

These placeholders were removed in versions newer of the expansion that 1.5.2. This was due to them producing a lot of lag.

Now. You have 2 options:
- You either downgrade to the Vault-Expansion 1.5.2, and go to `plugins/PlaceholderAPIconfig.yml` and enable: `expansions.vault.baltop.enabled`

- Or you go to our discord server: discord.gg/helpchat in the #placeholder-api channel and download the development builds for the Essentials Expansion. The placeholders required for baltop are also listed there.
